
package main.resources;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "mediaanFault", targetNamespace = "http://www.mediaanservice.org/fault")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MediaanFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Fault(String message, MediaanFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Fault(String message, MediaanFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: main.resources.MediaanFault
     */
    public MediaanFault getFaultInfo() {
        return faultInfo;
    }

}
