
package main.resources;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "mediaanServiceInterface", targetNamespace = "http://www.mediaanservice.org/mediaanservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MediaanServiceInterface {


    /**
     * 
     * @param request
     * @return
     *     returns main.resources.Result
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://www.mediaanservice.org/response", partName = "response")
    public Result calculateMediaan(
        @WebParam(name = "nummers", targetNamespace = "http://www.mediaanservice.org/request", partName = "request")
        Nummers request)
        throws Fault
    ;

}
