<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	name="MediaanService"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:req="http://www.mediaanservice.org/request"
	xmlns:rsp="http://www.mediaanservice.org/response"
	xmlns:flt="http://www.mediaanservice.org/fault"
	xmlns:tns="http://www.mediaanservice.org/mediaanservice"
	targetNamespace="http://www.mediaanservice.org/mediaanservice">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.mediaanservice.org/request"
			schemaLocation="MediaanServiceRequest.xsd"/>
			<xsd:import namespace="http://www.mediaanservice.org/response"
			schemaLocation="MediaanServiceResponse.xsd"/>
			<xsd:import namespace="http://www.mediaanservice.org/fault"
				schemaLocation="MediaanFault.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="request"> 
		<wsdl:part name="request" element="req:nummers"/> 
	</wsdl:message> 
	<wsdl:message name="response"> 
		<wsdl:part name="response" element="rsp:result"/> 
	</wsdl:message>
	<wsdl:message name="fault">
		<wsdl:part name="fault" element="flt:mediaanFault"/>
	</wsdl:message>
	
	<wsdl:portType name="mediaanServiceInterface">
		<wsdl:operation name="calculateMediaan">
			<wsdl:input message="tns:request"/>
			<wsdl:output message="tns:response"/>
			<wsdl:fault name="ApplicatieFout" message="tns:fault"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="mediaanServiceBinding" type="tns:mediaanServiceInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="calculateMediaan">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="ApplicatieFout">
				<soap:fault name="ApplicatieFout" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="mediaanService">
		<wsdl:port name="WS-Port" binding="tns:mediaanServiceBinding">
			<soap:address location="/services/mediaanService"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>